version: '3.7'

services: 
  db:
    image: mongo:${TAG}
    restart: always
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}