version: "3.7"

services: 
  gui:
    image: mongo-express:${TAG}
    restart: always
    depends_on: 
      - db
    ports: 
      - 8081:8081
    environment: 
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}