version: "3.7"

services:
  db:
    image: mcr.microsoft.com/mssql/server:${TAG}
    environment: 
      MSSQL_PID: ${MSSQL_VERSION}
      ACCEPT_EULA: Y
      SA_PASSWORD: ${ROOT_PASSWORD}
    ports: 
      - '1433:1433'

