version: "3.7"

services:
  db:
    image: couchdb:${TAG}
    restart: always
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: ${ROOT_USERNAME}
      COUCHDB_PASSWORD: ${ROOT_PASSWORD}
